### ISSUE TITLE
Create bootstrap image 

### ISSUE THREAD

**Issue by candreacchi** [defenseunicorns/zarf-package-bare-metal#2]
Would like to use Ubuntu minimal to run K3S on above.  We need to build an unique image that has the following pre-configured for install: 
- K3s from Zarf init 
- PXE & DHCP (another pair is working) 

Research needed into creating ISO and how we add in above items.  Need to think through packaging on a bootable USB.

**Comment by btlghrants** [comment]
Talk about how to make a custom image from an Ubuntu LiveCD: https://help.ubuntu.com/community/LiveCDCustomization

Not 100%, but... I _think_ we should be able to use it as a starter / as something to run an autoinstall from.

**Comment by btlghrants** [comment]
Notes from Kick-off:
- Start with vanilla Server ISO & write to USB
- Create second, file-xfer partition on USB
- Put zarf init package + images onto file-xfer partition
- Write autoinstall script that can mount the file-xfer partition & install software
