### ISSUE TITLE
Loading/installing zarf packages from an HTTP server post-install

### ISSUE THREAD

**Issue by candreacchi** [defenseunicorns/zarf-package-bare-metal#3]
We need to create an ISO that can boot Ubuntu and then select, download and install a zarf package from an http server (eventually the same from the PXE server implementation).

**Comment by Racer159** [comment]
This is specifically related to handling roles with cloud init and pxe.

**Comment by Racer159** [comment]
Finished, but needs integration with the Zarf PXE package
