### ISSUE TITLE
Integrate the Zarf PXE package with the USB bootstrap

### ISSUE THREAD

**Issue by Racer159** [defenseunicorns/zarf-package-bare-metal#5]
We need to integrate the USB bootstrap work with the Zarf PXE package to complete the end to end laydown of deploying Zarf onto bare metal.

**Comment by btlghrants** [comment]
With the inclusion of:
- https://github.com/defenseunicorns/zarf-package-bare-metal/blob/main/zarf-bootstrap-usb/03_build_zarf.sh, and 
- https://github.com/defenseunicorns/zarf-package-bare-metal/blob/main/zarf-bootstrap-usb/04_load_usb.sh

last night & this morning, I think we have a rudimentary form of this working.  Good enough to close this out, you think @Racer159 ?

**Comment by Racer159** [comment]
Completed.

**Comment by btlghrants** [comment]
For what it's worth: the reason Zarf wasn't successfully starting was due to calling `zarf package deploy` with a '--set K3S_ARGS=""' (which I ripped from _somewhere_-I-don't-remember-anymore) which was causing Traefik to start... which caused a port 80 conflict.  Removing the flag fixed it all up.
