### ISSUE TITLE
Look at dnsmasq replacements (MAAS)

### ISSUE THREAD

**Issue by docandrew** [defenseunicorns/zarf-package-bare-metal#9]
dnsmasq offers dhcpd and tftpd in a single binary, which is convenient but is not always the most friendly tool re: configuration options, and though we've disabled DNS serving on it, there may be a conflict between it and systemd-resolved.

**Comment by corang** [comment]
I would recommend replacing with two containers, one that runs some variant of dhcpd and another that runs tftp-hpa.

**Comment by Racer159** [comment]
We should look at https://maas.io/ for this https://github.com/naps-dev/maas-ctl

**Comment by Racer159** [comment]
Determined MAAS is what we want to use for now
